version: '3'

services:
  flaskapp:
    build: ./flask-app
    container_name: flaskapp
    ports:
      - "8000:8000"
    network_mode: host

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=$${IP}
    restart: always
    network_mode: host